- hosts: servers
  vars_files:
    - vars.yml

  tasks:
    - name: Install system packages
      apt: pkg={{ item }} update-cache=yes
      with_items: "{{ system_packages }}"


#- include: deploy.yml